################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c \
G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c \
G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c \
G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_exti.c \
G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.c \
G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash_ex.c \
G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c \
G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.c \
G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pwr.c \
G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c \
G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc_ex.c \
G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c \
G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c 

OBJS += \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal.o \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_cortex.o \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_dma.o \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_exti.o \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_flash.o \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_flash_ex.o \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_gpio.o \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_gpio_ex.o \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_pwr.o \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_rcc.o \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_rcc_ex.o \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_tim.o \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_tim_ex.o 

C_DEPS += \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal.d \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_cortex.d \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_dma.d \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_exti.d \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_flash.d \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_flash_ex.d \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_gpio.d \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_gpio_ex.d \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_pwr.d \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_rcc.d \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_rcc_ex.d \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_tim.d \
./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_tim_ex.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal.o: G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c Drivers/STM32F1xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_cortex.o: G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c Drivers/STM32F1xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_cortex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_dma.o: G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c Drivers/STM32F1xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_dma.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_exti.o: G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_exti.c Drivers/STM32F1xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_exti.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_flash.o: G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.c Drivers/STM32F1xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_flash.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_flash_ex.o: G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash_ex.c Drivers/STM32F1xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_flash_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_gpio.o: G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c Drivers/STM32F1xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_gpio.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_gpio_ex.o: G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.c Drivers/STM32F1xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_gpio_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_pwr.o: G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pwr.c Drivers/STM32F1xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_pwr.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_rcc.o: G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c Drivers/STM32F1xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_rcc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_rcc_ex.o: G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc_ex.c Drivers/STM32F1xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_rcc_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_tim.o: G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c Drivers/STM32F1xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_tim.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_tim_ex.o: G:/Faculty\ Of\ Engineering/4th\ Communication/Graduation\ Project/OneDrive\ -\ Alexandria\ University/Team\ 7/Resources/Courses/MOOC\ -\ STM32CubeMX\ and\ STM32Cube\ HAL\ basics/Projects/20220306_Timer_Test_1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c Drivers/STM32F1xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F103xB -c -I../../Core/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc -I../../Drivers/STM32F1xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32F1xx/Include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_tim_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

clean: clean-Drivers-2f-STM32F1xx_HAL_Driver

clean-Drivers-2f-STM32F1xx_HAL_Driver:
	-$(RM) ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal.d ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal.o ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_cortex.d ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_cortex.o ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_dma.d ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_dma.o ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_exti.d ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_exti.o ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_flash.d ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_flash.o ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_flash_ex.d ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_flash_ex.o ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_gpio.d ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_gpio.o ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_gpio_ex.d ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_gpio_ex.o ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_pwr.d ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_pwr.o ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_rcc.d ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_rcc.o ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_rcc_ex.d ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_rcc_ex.o ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_tim.d ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_tim.o ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_tim_ex.d ./Drivers/STM32F1xx_HAL_Driver/stm32f1xx_hal_tim_ex.o

.PHONY: clean-Drivers-2f-STM32F1xx_HAL_Driver

